function to display results

In [1]:
print("Hello world!")

Hello world!


In [2]:
print("Hello world!", "I'm Andrea", 3, 0.5)

Hello world! I'm Andrea 3 0.5


#### Variables

named entities to store information

In [3]:
a = 2

In [4]:
type(a)

int

In [5]:
b = 0.2

In [6]:
type(b)

float

In [7]:
c = '10'

In [8]:
type(c)

str

In [9]:
float(c)

10.0

In [10]:
d = 'okokok'

In [11]:
float(d)

ValueError: could not convert string to float: 'okokok'

#### Numeric Operations

In [12]:
a = 5
b = 2
a,b

(5, 2)

In [13]:
a + b

7

In [14]:
a - b

3

In [15]:
a * b

10

In [16]:
a / b

2.5

In [17]:
a // b # floor division
## returns only integer part of the result

2

In [18]:
a % b # module (rest by integer division)

1

In [19]:
a ** b # exponentiation operator

25

#### Strings

In [20]:
s = "this is a string"
s

'this is a string'

In [21]:
len(s)

16

In [22]:
s + ' Andrea'

'this is a string Andrea'

In [23]:
r = s.replace("a", "THE")
r

'this is THE string'

In [24]:
r.upper()

'THIS IS THE STRING'

In [25]:
r.lower()

'this is the string'

In [26]:
s[0]

't'

In [27]:
s[1]

'h'

In [28]:
s[-1]

'g'

In [29]:
s[-2]

'n'

In [30]:
s[16]

IndexError: string index out of range

In [31]:
s[0:4]

'this'

In [32]:
s[5:10]

'is a '

#### Data Structures: Lists

In [33]:
my_first_list = [1, 3, 5, 10]

In [34]:
type(my_first_list)

list

In [35]:
my_first_list

[1, 3, 5, 10]

In [36]:
len(my_first_list)

4

In [37]:
my_first_list[0:2]

[1, 3]

In [38]:
my_first_list[-1]

10

In [39]:
foo = my_first_list + [9, 10, 3]

In [40]:
foo

[1, 3, 5, 10, 9, 10, 3]

In [41]:
my_first_set = set([1, 2, 5, 7, 7])

In [42]:
my_first_set

{1, 2, 5, 7}

In [43]:
my_first_set[0]

TypeError: 'set' object is not subscriptable

In [44]:
my_second_list = [3, 1.2, 'Andrea', False]

In [45]:
my_second_list

[3, 1.2, 'Andrea', False]

In [46]:
my_second_list.append('okokok')

In [47]:
my_second_list

[3, 1.2, 'Andrea', False, 'okokok']

In [48]:
my_second_set = set(my_second_list)

In [49]:
my_second_set

{1.2, 3, 'Andrea', False, 'okokok'}

In [50]:
type(my_second_set)

set

In [51]:
my_first_list.append(8)

In [52]:
my_first_list

[1, 3, 5, 10, 8]

In [53]:
my_second_list.append(my_first_list)

In [54]:
my_second_list

[3, 1.2, 'Andrea', False, 'okokok', [1, 3, 5, 10, 8]]

In [55]:
my_second_list[5]

[1, 3, 5, 10, 8]

In [56]:
# list functions

In [57]:
aaa = [1,2,3]
bbb = [3,4,5]

In [58]:
aaa + bbb

[1, 2, 3, 3, 4, 5]

In [59]:
ccc = aaa + bbb

In [60]:
aaa.append(3)

In [61]:
aaa

[1, 2, 3, 3]

In [62]:
aaa.extend(bbb)

In [63]:
aaa

[1, 2, 3, 3, 3, 4, 5]

In [64]:
# tuple
my_first_tuple = (1,2,3,3)

In [65]:
my_first_tuple # can contain duplicates

(1, 2, 3, 3)

In [66]:
my_first_tuple[0] # ordered can access by index

1

In [67]:
list(my_first_tuple)

[1, 2, 3, 3]

In [68]:
set(my_first_tuple) # does not contain duplicates

{1, 2, 3}

In [69]:
set(my_first_tuple)[0] # not ordered

TypeError: 'set' object is not subscriptable

In [70]:
my_first_tuple + (1,3)

(1, 2, 3, 3, 1, 3)

In [71]:
my_first_tuple * (3)

(1, 2, 3, 3, 1, 2, 3, 3, 1, 2, 3, 3)

In [72]:
set(my_first_tuple) | {2,3} # union operation

{1, 2, 3}

In [73]:
set(my_first_tuple) * {2,3}

TypeError: unsupported operand type(s) for *: 'set' and 'set'

In [74]:
my_first_tuple.append(0) # tuple not mutable

AttributeError: 'tuple' object has no attribute 'append'

In [75]:
my_set = set(my_first_tuple)
my_set

{1, 2, 3}

In [76]:
my_set.add(0)

In [77]:
my_set

{0, 1, 2, 3}

#### Dictionaries
mutable

In [78]:
my_first_dict = {'Andrea': 10, 'Marco': 12, 'Clarissa': 16, 'Nicoletta':2}

In [79]:
my_first_dict

{'Andrea': 10, 'Marco': 12, 'Clarissa': 16, 'Nicoletta': 2}

In [80]:
my_first_dict['Andrea']

10

In [81]:
my_first_dict['Clarissa']

16

In [82]:
aaa = {1: 'Riccardo', 2: 'Andrea', 3: 'Dino'}

In [83]:
aaa[1]

'Riccardo'

In [84]:
aaa[0] = 'Alessandro'

In [85]:
aaa

{1: 'Riccardo', 2: 'Andrea', 3: 'Dino', 0: 'Alessandro'}

In [86]:
aaa[0] = 'Giuseppe'

In [87]:
aaa

{1: 'Riccardo', 2: 'Andrea', 3: 'Dino', 0: 'Giuseppe'}

In [88]:
len(aaa)

4

In [89]:
aaa.keys()

dict_keys([1, 2, 3, 0])

In [90]:
list(aaa.keys())

[1, 2, 3, 0]

In [91]:
aaa.values()

dict_values(['Riccardo', 'Andrea', 'Dino', 'Giuseppe'])

In [92]:
list(aaa.values())

['Riccardo', 'Andrea', 'Dino', 'Giuseppe']

In [93]:
aaa.items()

dict_items([(1, 'Riccardo'), (2, 'Andrea'), (3, 'Dino'), (0, 'Giuseppe')])

In [94]:
for key, value in aaa.items():
    print(key, value)

1 Riccardo
2 Andrea
3 Dino
0 Giuseppe


#### Conditional
if-else

In [95]:
a = 30
if a >= 25:
    b = 'Happy'
    print('Here')
else:
    b = 'Sad'
    print('There')
    
print('I\'m %s because I got %s to DM exam.' % (b, a))

Here
I'm Happy because I got 30 to DM exam.


In [96]:
a >= 25

True

In [97]:
a = 24
if 20 <= a < 25:
    print('AAAA')

AAAA


In [98]:
a > 30

False

#### loops

In [99]:
my_first_list

[1, 3, 5, 10, 8]

In [ ]:
print(my_first_list[0])
print(my_first_list[1])
print(my_first_list[2])
...
print(my_first_list[7])

In [100]:
for e in my_first_list:
    if e > 5:
        print(e)
    else:
        print('ooo')

ooo
ooo
ooo
10
8


In [101]:
for idx, e in enumerate(my_first_list):
    print(idx, e)

0 1
1 3
2 5
3 10
4 8


In [102]:
for i in range(len(my_first_list)):
    print(i, my_first_list[i])

0 1
1 3
2 5
3 10
4 8


In [103]:
for k, v in my_first_dict.items():
    print(k, v)

Andrea 10
Marco 12
Clarissa 16
Nicoletta 2


#### Modules

In [104]:
# zen of python
# 19 principles for python

In [105]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [106]:
import math

In [107]:
math.pi

3.141592653589793

In [108]:
math.log2(1456)

10.507794640198696

In [109]:
import numpy as np
# aliasing
# handles array and calculus
# fast, memory handeled well

In [110]:
my_first_array = np.array(my_first_list)

In [111]:
my_first_array

array([ 1,  3,  5, 10,  8])

In [112]:
my_first_list * 5

[1,
 3,
 5,
 10,
 8,
 1,
 3,
 5,
 10,
 8,
 1,
 3,
 5,
 10,
 8,
 1,
 3,
 5,
 10,
 8,
 1,
 3,
 5,
 10,
 8]

In [113]:
# pairwise operation
my_first_array * 5

array([ 5, 15, 25, 50, 40])

In [114]:
my_first_array / 5

array([0.2, 0.6, 1. , 2. , 1.6])

In [115]:
my_first_array + my_first_array

array([ 2,  6, 10, 20, 16])

In [116]:
# other ways of creating loops

In [117]:
for i in np.arange(1, 20, 5):
    print(i)

1
6
11
16


In [118]:
np.arange(5, 10, 2)

array([5, 7, 9])

In [119]:
range(10)

range(0, 10)

In [120]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9
